/**
 * GlueStack UI Configuration — mirrors active semantic colors (C).
 * @see constants/palette.js
 */
import { C as defaultColors, P } from './constants/palette';

/**
 * @param {typeof defaultColors} colors
 */
export function createGluestackConfig(colors) {
  return {
    tokens: {
      colors: {
        bg: colors.bg,
        surface: colors.surface,
        surfaceTint: colors.surfaceTint,
        primary: colors.primary,
        primaryHover: colors.primaryPressed,
        primaryPressed: colors.primaryPressed,
        accent: colors.accent,
        accentHover: colors.accentPressed,
        accentPressed: colors.accentPressed,
        delight: colors.delight,
        positive: colors.positive,
        positiveBg: colors.positiveBg,
        positiveBorder: colors.positiveBorder,
        warning: colors.warning,
        warningBg: colors.warningBg,
        warningBorder: colors.warningBorder,
        cycleWarning: colors.cycleWarning,
        danger: colors.danger,
        dangerBg: colors.dangerBg,
        dangerBorder: colors.dangerBorder,
        debt: colors.debt,
        text: colors.text,
        muted: colors.muted,
        border: colors.border,
        divider: colors.border,
        placeholder: colors.muted,
        disabled: colors.disabled,
        white: P.light?.white ?? '#FFFFFF',
        black: '#000000',

        selectedBg: colors.selectedBg,
        selectedText: colors.selectedText,
        chipSelectedBg: colors.selectedBg,
        chipSelectedBorder: colors.primary,
        chipSelectedText: colors.selectedText,
        navSelectedBg: colors.navSelectedBg,
        navSelectedBorder: colors.border,
        infoWashBg: colors.surfaceTint,
        infoWashBorder: colors.border,
        insightCardBg: colors.insightCardBg,
        insightCardBorder: colors.insightCardBorder,
        insightGlow: colors.accent,
        chipActive: colors.overlaySelected,
        chipActiveBorder: colors.primary,

        progressTrack: colors.progressTrack,
        progressFill: colors.progressFill,

        pillSelectedBg: colors.accent,
        pillSelectedPressed: colors.accentPressed,
        pillSelectedText: colors.selectedText,
        pillUnselectedBg: colors.surface,
        pillUnselectedBorder: colors.border,
        pillUnselectedText: colors.muted,

        infoBg: colors.infoBg,
        infoBorder: colors.infoBorder,
        infoText: colors.info,

        addBorder: colors.accent,
        addText: colors.accent,
        addPressed: colors.bg,

        overlayHover: colors.overlayHover,
        overlayPressed: colors.overlayPressed,
        overlaySelected: colors.overlaySelected,

        error: colors.danger,
        success: colors.positive,
        info: colors.accent,
      },
      space: {
        '1': 4,
        '2': 8,
        '3': 12,
        '3.5': 14,
        '4': 16,
        '4.5': 18,
        '5': 20,
        '6': 24,
        '7': 28,
        '8': 32,
        '10': 40,
        '12': 48,
        '16': 64,
        pagePadH: 20,
        pagePadV: 24,
        cardPad: 20,
        fieldGap: 16,
        labelGap: 6,
        sectionGap: 24,
        navHeight: 56,
        progressHeight: 3,
      },
      radii: {
        none: 0,
        xs: 4,
        sm: 6,
        md: 8,
        lg: 22,
        xl: 22,
        '2xl': 22,
        '3xl': 22,
        full: 999,
        input: 22,
        card: 22,
        button: 99,
        pill: 99,
        chip: 16,
      },
      fontSizes: {
        '2xs': 11,
        xs: 12,
        sm: 13,
        md: 15,
        lg: 17,
        xl: 22,
        '2xl': 24,
        '3xl': 28,
        '4xl': 40,
      },
      lineHeights: {
        '2xs': 14,
        xs: 18,
        sm: 20,
        md: 23,
        lg: 26,
        xl: 32,
        '2xl': 34,
        '3xl': 44,
      },
      fontWeights: {
        normal: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
      },
      fonts: {
        heading: 'GeneralSans-Regular',
        body: 'GeneralSans-Regular',
        mono: 'DM Mono',
      },
    },
  };
}

export const config = createGluestackConfig(defaultColors);
